# Version management for ZeroComp
# This file centralizes version information

file(READ "${CMAKE_SOURCE_DIR}/VERSION" ZEROCOMP_VERSION_STRING)
string(STRIP "${ZEROCOMP_VERSION_STRING}" ZEROCOMP_VERSION_STRING)

string(REGEX MATCH "^([0-9]+)\\.([0-9]+)\\.([0-9]+)(-(.+))?$" VERSION_MATCH "${ZEROCOMP_VERSION_STRING}")

if(VERSION_MATCH)
    set(ZEROCOMP_VERSION_MAJOR ${CMAKE_MATCH_1})
    set(ZEROCOMP_VERSION_MINOR ${CMAKE_MATCH_2})
    set(ZEROCOMP_VERSION_PATCH ${CMAKE_MATCH_3})

    if(CMAKE_MATCH_5)
        set(ZEROCOMP_VERSION_SUFFIX ${CMAKE_MATCH_5})
        set(ZEROCOMP_VERSION_FULL "${ZEROCOMP_VERSION_MAJOR}.${ZEROCOMP_VERSION_MINOR}.${ZEROCOMP_VERSION_PATCH}-${ZEROCOMP_VERSION_SUFFIX}")
    else()
        set(ZEROCOMP_VERSION_SUFFIX "")
        set(ZEROCOMP_VERSION_FULL "${ZEROCOMP_VERSION_MAJOR}.${ZEROCOMP_VERSION_MINOR}.${ZEROCOMP_VERSION_PATCH}")
    endif()
else()
    message(FATAL_ERROR "Invalid version format in VERSION file: ${ZEROCOMP_VERSION_STRING}")
endif()

set(PROJECT_VERSION "${ZEROCOMP_VERSION_MAJOR}.${ZEROCOMP_VERSION_MINOR}.${ZEROCOMP_VERSION_PATCH}")
set(PROJECT_VERSION_MAJOR ${ZEROCOMP_VERSION_MAJOR})
set(PROJECT_VERSION_MINOR ${ZEROCOMP_VERSION_MINOR})
set(PROJECT_VERSION_PATCH ${ZEROCOMP_VERSION_PATCH})

if(NOT CMAKE_CURRENT_SOURCE_DIR STREQUAL CMAKE_SOURCE_DIR)
    set(ZEROCOMP_VERSION ${ZEROCOMP_VERSION_FULL} PARENT_SCOPE)
endif()

message(STATUS "ZeroComp Version: ${ZEROCOMP_VERSION_FULL}")
message(STATUS "  Major: ${ZEROCOMP_VERSION_MAJOR}")
message(STATUS "  Minor: ${ZEROCOMP_VERSION_MINOR}")
message(STATUS "  Patch: ${ZEROCOMP_VERSION_PATCH}")
if(ZEROCOMP_VERSION_SUFFIX)
    message(STATUS "  Suffix: ${ZEROCOMP_VERSION_SUFFIX}")
endif()
